name: super_editor
description: Configurable, composable, extensible text editor and document renderer for Flutter.
version: 0.2.2
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.2.0
  collection: ^1.15.0
  http: ^0.13.1
  linkify: ^4.0.0
  logging: ^1.0.1
  attributed_text:
    git:
      url: https://github.com/DinhNam99/attributed_text.git
  super_text_layout:
    git:
      url: https://github.com/DinhNam99/super_text_layout.git
  uuid: ^3.0.3

  # Dependencies for testing tools that we ship with super_editor
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  # no Flutter configuration
